style:
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlinx.coroutines.Dispatchers.IO'
      - 'kotlinx.coroutines.Dispatchers.Default'
      - 'kotlinx.coroutines.Dispatchers.Main'
    excludes:
      - '**/data/remote/di/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/build-logic/**'
  ForbiddenImport:
    active: true
    imports:
      - 'androidx.lifecycle.ViewModel'
    excludes:
      - '**/core/presentation/**'
      - '**/app/**'
      - '**/feature/**/presentation/**'
